// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: markFeedFetched.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const markFeedFetched = `-- name: MarkFeedFetched :exec
update feeds
set last_fetched_at=now(),
    updated_at=now()
where id = $1
`

func (q *Queries) MarkFeedFetched(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markFeedFetched, id)
	return err
}
